// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDibETXExJ9hymXd-HV-ZWTj6D3UNvejHw',
    appId: '1:642351661219:web:340e99e7124a38dafb3f16',
    messagingSenderId: '642351661219',
    projectId: 'nipedealweb-c9e5f',
    authDomain: 'nipedealweb-c9e5f.firebaseapp.com',
    storageBucket: 'nipedealweb-c9e5f.appspot.com',
    measurementId: 'G-YTG65LM1X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVI8Gj7UQx3zRPareJHW6Ng2dExzvrSTo',
    appId: '1:642351661219:android:7775f624a9bf0481fb3f16',
    messagingSenderId: '642351661219',
    projectId: 'nipedealweb-c9e5f',
    storageBucket: 'nipedealweb-c9e5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUzQlqObvi2bYDVZ7oVD5OYgS2Q3sy9kA',
    appId: '1:642351661219:ios:39973b05f7f90444fb3f16',
    messagingSenderId: '642351661219',
    projectId: 'nipedealweb-c9e5f',
    storageBucket: 'nipedealweb-c9e5f.appspot.com',
    iosBundleId: 'com.example.nipedealweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUzQlqObvi2bYDVZ7oVD5OYgS2Q3sy9kA',
    appId: '1:642351661219:ios:39973b05f7f90444fb3f16',
    messagingSenderId: '642351661219',
    projectId: 'nipedealweb-c9e5f',
    storageBucket: 'nipedealweb-c9e5f.appspot.com',
    iosBundleId: 'com.example.nipedealweb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDibETXExJ9hymXd-HV-ZWTj6D3UNvejHw',
    appId: '1:642351661219:web:7ec5c7679ed52b85fb3f16',
    messagingSenderId: '642351661219',
    projectId: 'nipedealweb-c9e5f',
    authDomain: 'nipedealweb-c9e5f.firebaseapp.com',
    storageBucket: 'nipedealweb-c9e5f.appspot.com',
    measurementId: 'G-45Y3VXRPWH',
  );
}
